version: "3"
services:
  kafka-stack:
    # This will serve as our Kafka stack
    image: landoop/fast-data-dev:2.5.1
    environment:
      - FORWARDLOGS=0
      - RUNTESTS=0
      - ADV_HOST=localhost
    ports:
      - 3030:3030
      - 2181:2181
      - 8081-8083:8081-8083
      - 9581-9585:9581-9585
      - 9092:9092
